# # yaml-language-server: $schema=https://my.url.to/the/schema

domain: anexample.com

records:
  A:
    - name: "@"
      value: "127.0.0.1"
      ttl: 9001
    - name: "boop.anexample.com"
      value: "8.8.8.8"
  TXT:
    - name: "@"
      value: "v=spf1 include:spf.messagingengine.com ?all"
    - name: "@"
      value: "another in recordset"
      ttl: 600
    - name: "api"
      value: "127.0.0.1"
  CNAME:
    - name: "wow"
      value: "google.com."
    - name: "wee"
      value: "google.com"
  MX:
    - name: "beep"
      value: "in1-smtp.messagingengine.com."
      priority: 20

atproto:
  - handle: "@anexample.com"
    did: "did=did:plc:lodvu673l7mrw3tyevt7vl4e"
  - handle: "beingthecowboy.anexample.com"
    did: "did:plc:mgirdry3xewuqjnknhkxxphd"
  - handle: "@me.anexample.com"
    did: "did:plc:eeeeeeeeeeeeeeeeeeeeeeee"
